### ISSUE TITLE
A non-catched exception for a non-timestamp token in python 3.10.15

### ISSUE THREAD

**Issue by AethliosIK** [AethliosIK/reset-tolkien#16]
Stack trace:

```bash
$ reset-tolkien detect [REDACTED] -d "Fri, 15 Sep 2023 23:55:15 GMT" --threads 32 --float-timestamp-range 1 --decimal-length 5
  0%|                                                                                                                                                                                      | 0/120 [00:00<?, ?it/s]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/format.py", line 424, in hashing_with_prefix
    encoded_timestamp = self.encode(
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/format.py", line 387, in encode
    token = format(
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/format.py", line 217, in datetime
    return from_microsecond_timestamp(
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/utils.py", line 296, in from_microsecond_timestamp
    raise ValueError("Not a timestamp")
ValueError: Not a timestamp
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/reset-tolkien", line 33, in <module>
    sys.exit(load_entry_point('reset-tolkien==1.3.0', 'console_scripts', 'reset-tolkien')())
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/cli.py", line 337, in main
    results = tolkien.detectFormat(
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/resetTolkien.py", line 345, in detectFormat
    return self._detectFormat(self.token, nb_threads, timestamp=timestamp)
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/resetTolkien.py", line 321, in _detectFormat
    r = self.detectHash(
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/resetTolkien.py", line 176, in detectHash
    self.formatter.multithread_decrypt(
  File "/usr/local/lib/python3.10/site-packages/reset_tolkien-1.3.0-py3.10.egg/resetTolkien/format.py", line 484, in multithread_decrypt
    for (
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
ValueError: Not a timestamp

```

**Comment by AethliosIK** [comment]
Implemented in https://github.com/AethliosIK/reset-tolkien/pull/18

**Comment by AethliosIK** [comment]
Fixed in https://github.com/AethliosIK/reset-tolkien/pull/20
